name: optic
on:
  #pull_request:
  push:
    branches:
      - "main"
 
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      step2: ${{ steps.step2.outputs.apitype }}
    steps:
      - name: Checkout repository
        id: step1
        uses: actions/checkout@v3
      
      - name: Validate if is API UX
        id: step3
        run: |
          apitype2=`yq '.x-bcp-api-type' openapi_petstore_2.yaml`
          if [ $apitype2 == 'UX' ]; then
            echo "This API is UX. It's will start to validate if this change is a fix..."
            go install github.com/tufin/oasdiff@latest
            echo "OASDIFF_NO_TELEMETRY=1" >> $GITHUB_ENV
            oasdiff diff openapi_petstore.yaml openapi_petstore_2.yaml
          else
            echo "This API is not UX. It's not allowed push to DEVELOP. API Governance requires review the API."
          fi

      #- name: Install Optic
        #run: npm install --location global @useoptic/optic
 
      #- name: Optic diff
        #run: optic diff https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore_2.yaml