name: optic
on:
  #pull_request:
  push:
    branches:
      - "main"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: step1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Validate if is fix
        id: step2
        run: |
          echo "1. Validating if this API is UX..."
          apitype=`yq '.x-bcp-api-type' api/openapi_petstore_2.yaml`
          if [ $apitype == 'UX' ]; then
            echo "2. This API is UX. Validating if this repo of API has a tag v1.0.0 (if not is a new API)..."
            TAG="v1.0.0"
            if git show-ref --tags --verify "refs/tags/${TAG}"; then
              echo "3. The tag ${TAG} exists. Validating if this is a FIX..."
              npm i -g @pb33f/openapi-changes
              result=`openapi-changes report --no-color api/openapi_petstore.yaml api/openapi_petstore_2.yaml`
              echo result: $result

            else
              echo "3. Tag tag ${TAG} doesn't exist. So this is a new API UX, then API Governance requires review it."
              
            fi
            
          else
            echo "2. This API is not UX. It's not allowed push to DEVELOP. API Governance requires review the API."
          fi

      #- name: Install Optic
        #run: npm install --location global @useoptic/optic
 
      #- name: Optic diff
        #run: optic diff https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore_2.yaml