name: optic
on:
  #pull_request:
  push:
    branches:
      - "main"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: step1
        uses: actions/checkout@v3
      
      - name: Validate if is fix
        id: step2
        run: |
          apitype=`yq '.x-bcp-api-type' /api/openapi_petstore_2.yaml`
          if [ $apitype == 'UX' ]; then
            echo "This API is UX. It's will start to validate if this change is a fix..."
            npm i -g @pb33f/openapi-changes
            openapi-changes report /api/openapi_petstore.yaml /api/openapi_petstore_2.yaml
          else
            echo "This API is not UX. It's not allowed push to DEVELOP. API Governance requires review the API."
          fi

      #- name: Install Optic
        #run: npm install --location global @useoptic/optic
 
      #- name: Optic diff
        #run: optic diff https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore_2.yaml