name: optic
on:
  #pull_request:
  push:
    branches:
      - "main"
 
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      step2: ${{ steps.step2.outputs.apitype }}
    steps:
      - name: Checkout
        id: step1
        uses: actions/checkout@v3

      - name: Set output variables
        id: step2
        run: |
          echo "apitype=hello" >> "$GITHUB_OUTPUT"
      
      - name: Use utput variables
        id: step3
        run: |
          echo ${{ steps.step2.outputs.apitype }}

      #- name: Install Optic
        #run: npm install --location global @useoptic/optic
 
      #- name: Optic diff
        #run: optic diff https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore_2.yaml