name: optic
on:
  #pull_request:
  push:
    branches:
      - "main"
 
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      step2: ${{ steps.step2.outputs.apitype }}
    steps:
      - name: Checkout repository
        id: step1
        uses: actions/checkout@v3

      - name: Get api type
        id: step2
        run: |
          echo "apitype=`yq '.x-bcp-api-type' openapi_petstore_2.yaml`" >> "$GITHUB_OUTPUT"
      
      - name: Use utput variables
        id: step3
        run: |
          if [ ${{ steps.step2.outputs.apitype }} == 'UX' ]; then
            echo "Se iniciara validacion si es un FIX..."
          else
            echo "It's not allowed push to DEVELOP. API Governance requires review the API"
          fi

      #- name: Install Optic
        #run: npm install --location global @useoptic/optic
 
      #- name: Optic diff
        #run: optic diff https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/openapi_petstore_2.yaml