name: workflow_api_fix
on:
  #pull_request:
  push:
    branches:
      - "bugfix/*"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Validar si es nueva API
        id: new_api
        run: |
          echo "1. Validando si es nueva API."
          resu=`git ls-remote origin --quiet v\*`
          # Si no existe ningun tag en github que empiece con v (ejm: v1.0.0)
          if [[ -z "${resu// /}" ]]; then
            result="TRUE"
            echo "No existen tags de formato vX.Y.Z, por tanto es nueva API"
          else 
            result="FALSE"
            echo "Existen tags de formato vX.Y.Z, por tanto NO es nueva API"
          fi
          echo "IS_NEW_API=$result" >> $GITHUB_OUTPUT

      - name: Instalar lib my-openapi-changes
        id: install_openapi_changes
        if: ${{ steps.new_api.outputs.IS_NEW_API == 'FALSE' }}
        run: |
          echo "2. Si es una actualizacion de API, se instala libreria para validar tipo de actualizacion en el OpenAPI"
          curl -fsSL https://raw.githubusercontent.com/devniel93/my-openapi-changes/main/install.sh | sh

      - name: Obtener nombre de repo
        id: get_repo_name
        if: ${{ steps.new_api.outputs.IS_NEW_API == 'FALSE' }}
        run: |
          gitRepoName=`git ls-remote --get-url | xargs basename -s .git`
          echo "GIT_REPO_NAME=$gitRepoName" >> $GITHUB_OUTPUT

      - name: Validar si es FIX
        id: is_fix
        if: ${{ steps.new_api.outputs.IS_NEW_API == 'FALSE' }}
        run: |
          gitRepoName=${{ steps.get_repo_name.outputs.GIT_REPO_NAME }}
          jsonReport=`openapi-changes report --no-color api/$gitRepoName.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/api/$gitRepoName.yaml`
          echo $jsonReport
          echo "IS_FIX_DESIGN='FALSE'" >> $GITHUB_OUTPUT

          validJson=`echo $jsonReport | jq -r '.message'`
          prefix="No changes"
          result=""
          if [[ $validJson == "$prefix"* ]]; then
            echo "No existen cambios"
            echo "exit"
          else
            echo "Existen cambios..."

            echo "2.0 validando si hay cambios en paths o endpoints"
            validFix=`echo $jsonReport | jq -r '.reportSummary.paths'`
            echo "2.0: $validFix"
            
            if [[ -z "${validFix// /}" ]] || [[ $validFix == 'null' ]] ; then
              echo "No hay cambios en paths o endpoints."
            
              IFS=',' read -r -a elementos <<< ${{ vars.OPENAPI_CHANGES_PROPERTIES }}
              for elemento in "${elementos[@]}"; do
                  echo "2.1 validando si hay cambios en $elemento"
                  validFix=`echo $jsonReport | jq -r '.changes[] | select(.property=="'$elemento'")'`
                  echo "2.1: $validFix"

                  if [[ -z "${validFix// /}" ]] || [[ $validFix == 'null' ]] ; then
                     echo "No hay cambios en $elemento"
                     result="TRUE"
                  else
                    echo "Hay cambios en $elemento"
                    result="FALSE"
                    break
                  fi
                  echo "IS_FIX_DESIGN=$result" >> $GITHUB_OUTPUT

              done
              
            else
              echo "Hay cambios en paths o endpoints."
              echo "exit"
            fi

          fi

      - name: Generar PR
        id: generate_pr
        if: ${{ steps.is_fix.outputs.IS_FIX_DESIGN == 'TRUE' }}
        run: |
          gh pr create --title 'Merge testing' --body 'Created by Github action'
          gh pr merge --merge
          # se elimina el branch automaticamente despues del pr merge. Esto por la configuracion en github de eliminar autom branch head
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get_latest_tag
        if: ${{ steps.generate_pr.outcome == 'success' }}
        with:
          semver_only: true

      - uses: actions-ecosystem/action-bump-semver@v1
        id: get_new_version
        if: ${{ steps.get_latest_tag.outcome == 'success' }}
        with:
          current_version: ${{ steps.get_latest_tag.outputs.tag }}
          level: 'minor'
      
      - uses: actions-ecosystem/action-push-tag@v1
        id: generate_tag
        if: ${{ steps.get_new_version.outputs.new_version != null }}
        with:
          tag: ${{ steps.get_new_version.outputs.new_version }}
          message: "${{ steps.get_new_version.outputs.new_version }}: PR"