name: workflow_api_fix
on:
  #pull_request:
  push:
    branches:
      - "bugfix/*"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Validar si es nueva API
        id: new_api
        run: |
          echo "1. Validando si es nueva API."
          resu=`git ls-remote origin --quiet v\*`
          if [[ -z "${resu// /}" ]]; then
            echo "TRUE"
          else 
            echo "FALSE"
          fi

      - name: Instalar lib my-openapi-changes
        id: install_openapi_changes
        run: |
          curl -fsSL https://raw.githubusercontent.com/devniel93/my-openapi-changes/main/install.sh | sh

      - name: Obtener nombre de repo
        id: get_repo_name
        run: |
          gitRepoName=`git ls-remote --get-url | xargs basename -s .git`
          echo "get_repo_name gitRepoName:$gitRepoName"
          echo `::set-output name=GIT_REPO_NAME::$gitRepoName`
          

      - name: Validar si existen cambios
        id: validate_for_changes
        run: |
          gitRepoName=${{ steps.get_repo_name.outputs.GIT_REPO_NAME }}
          echo "validate_for_changes gitRepoName:$gitRepoName"
          jsonReport=`openapi-changes report --no-color api/$gitRepoName.yaml https://raw.githubusercontent.com/devniel93/poc_openapi_breaking_changes/main/api/$gitRepoName.yaml`
          echo $jsonReport